#############################################################################
# Makefile for building: GrammarNN
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  GrammarNN.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile GrammarNN.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -Ofast -O2 -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -Ofast -std=c++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -Ofast -O2 -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -fopt-info -Ofast -std=c++11 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = GrammarNN1.0.0
DISTDIR = /home/sheridan/Desktop/ERGASIES/GrammarNN/.tmp/GrammarNN1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = CORE/parameter.cpp \
		CORE/parameterlist.cpp \
		GE/cprogram.cc \
		GE/doublestack.cc \
		GE/fparser.cc \
		GE/fpoptimizer.cc \
		GE/grammargenetic.cpp \
		GE/integeranneal.cpp \
		GE/program.cc \
		GE/rule.cc \
		GE/symbol.cc \
		INTERVAL/interval.cpp \
		INTERVAL/intervalde.cpp \
		INTERVAL/intervalproblem.cpp \
		INTERVAL/problem.cpp \
		METHODS/adam.cpp \
		METHODS/armijosearch.cpp \
		METHODS/bfgs.cpp \
		METHODS/collection.cpp \
		METHODS/doublebox.cpp \
		METHODS/editlogger.cpp \
		METHODS/fibonaccisearch.cpp \
		METHODS/filelogger.cpp \
		METHODS/genetic.cpp \
		METHODS/goldensearch.cpp \
		METHODS/gradientdescent.cpp \
		METHODS/ipso.cpp \
		METHODS/lbfgs.cpp \
		METHODS/linesearch.cpp \
		METHODS/logger.cpp \
		METHODS/mean.cpp \
		METHODS/optimizer.cpp \
		METHODS/similarity.cpp \
		MLMODELS/dataset.cpp \
		MLMODELS/mlpproblem.cpp \
		MLMODELS/model.cpp \
		MLMODELS/rbfproblem.cpp \
		SAMPLER/kmeanssampler.cpp \
		SAMPLER/maxwellsampler.cpp \
		SAMPLER/neuralsampler.cpp \
		SAMPLER/problemsampler.cpp \
		SAMPLER/rbfsampler.cpp \
		SAMPLER/triangularsampler.cpp \
		SAMPLER/uniformsampler.cpp \
		main.cpp 
OBJECTS       = parameter.o \
		parameterlist.o \
		cprogram.o \
		doublestack.o \
		fparser.o \
		fpoptimizer.o \
		grammargenetic.o \
		integeranneal.o \
		program.o \
		rule.o \
		symbol.o \
		interval.o \
		intervalde.o \
		intervalproblem.o \
		problem.o \
		adam.o \
		armijosearch.o \
		bfgs.o \
		collection.o \
		doublebox.o \
		editlogger.o \
		fibonaccisearch.o \
		filelogger.o \
		genetic.o \
		goldensearch.o \
		gradientdescent.o \
		ipso.o \
		lbfgs.o \
		linesearch.o \
		logger.o \
		mean.o \
		optimizer.o \
		similarity.o \
		dataset.o \
		mlpproblem.o \
		model.o \
		rbfproblem.o \
		kmeanssampler.o \
		maxwellsampler.o \
		neuralsampler.o \
		problemsampler.o \
		rbfsampler.o \
		triangularsampler.o \
		uniformsampler.o \
		main.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GrammarNN.pro CORE/parameter.h \
		CORE/parameterlist.h \
		GE/cprogram.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/fpconfig.hh \
		GE/fptypes.hh \
		GE/grammargenetic.h \
		GE/integeranneal.h \
		GE/program.h \
		GE/rule.h \
		GE/symbol.h \
		INTERVAL/interval.h \
		INTERVAL/intervalde.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/problem.h \
		METHODS/adam.h \
		METHODS/armijosearch.h \
		METHODS/bfgs.h \
		METHODS/collection.h \
		METHODS/doublebox.h \
		METHODS/editlogger.h \
		METHODS/fibonaccisearch.h \
		METHODS/filelogger.h \
		METHODS/genetic.h \
		METHODS/goldensearch.h \
		METHODS/gradientdescent.h \
		METHODS/ipso.h \
		METHODS/lbfgs.h \
		METHODS/linesearch.h \
		METHODS/logger.h \
		METHODS/mean.h \
		METHODS/optimizer.h \
		METHODS/similarity.h \
		MLMODELS/dataset.h \
		MLMODELS/mlpproblem.h \
		MLMODELS/model.h \
		MLMODELS/rbfproblem.h \
		SAMPLER/kmeanssampler.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h CORE/parameter.cpp \
		CORE/parameterlist.cpp \
		GE/cprogram.cc \
		GE/doublestack.cc \
		GE/fparser.cc \
		GE/fpoptimizer.cc \
		GE/grammargenetic.cpp \
		GE/integeranneal.cpp \
		GE/program.cc \
		GE/rule.cc \
		GE/symbol.cc \
		INTERVAL/interval.cpp \
		INTERVAL/intervalde.cpp \
		INTERVAL/intervalproblem.cpp \
		INTERVAL/problem.cpp \
		METHODS/adam.cpp \
		METHODS/armijosearch.cpp \
		METHODS/bfgs.cpp \
		METHODS/collection.cpp \
		METHODS/doublebox.cpp \
		METHODS/editlogger.cpp \
		METHODS/fibonaccisearch.cpp \
		METHODS/filelogger.cpp \
		METHODS/genetic.cpp \
		METHODS/goldensearch.cpp \
		METHODS/gradientdescent.cpp \
		METHODS/ipso.cpp \
		METHODS/lbfgs.cpp \
		METHODS/linesearch.cpp \
		METHODS/logger.cpp \
		METHODS/mean.cpp \
		METHODS/optimizer.cpp \
		METHODS/similarity.cpp \
		MLMODELS/dataset.cpp \
		MLMODELS/mlpproblem.cpp \
		MLMODELS/model.cpp \
		MLMODELS/rbfproblem.cpp \
		SAMPLER/kmeanssampler.cpp \
		SAMPLER/maxwellsampler.cpp \
		SAMPLER/neuralsampler.cpp \
		SAMPLER/problemsampler.cpp \
		SAMPLER/rbfsampler.cpp \
		SAMPLER/triangularsampler.cpp \
		SAMPLER/uniformsampler.cpp \
		main.cpp
QMAKE_TARGET  = GrammarNN
DESTDIR       = 
TARGET        = GrammarNN


first: all
####### Build rules

GrammarNN:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GrammarNN.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GrammarNN.pro
	$(QMAKE) -o Makefile GrammarNN.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
GrammarNN.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile GrammarNN.pro

qmake_all: FORCE


all: Makefile GrammarNN

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CORE/parameter.h CORE/parameterlist.h GE/cprogram.h GE/doublestack.h GE/fparser.hh GE/fpconfig.hh GE/fptypes.hh GE/grammargenetic.h GE/integeranneal.h GE/program.h GE/rule.h GE/symbol.h INTERVAL/interval.h INTERVAL/intervalde.h INTERVAL/intervalproblem.h INTERVAL/problem.h METHODS/adam.h METHODS/armijosearch.h METHODS/bfgs.h METHODS/collection.h METHODS/doublebox.h METHODS/editlogger.h METHODS/fibonaccisearch.h METHODS/filelogger.h METHODS/genetic.h METHODS/goldensearch.h METHODS/gradientdescent.h METHODS/ipso.h METHODS/lbfgs.h METHODS/linesearch.h METHODS/logger.h METHODS/mean.h METHODS/optimizer.h METHODS/similarity.h MLMODELS/dataset.h MLMODELS/mlpproblem.h MLMODELS/model.h MLMODELS/rbfproblem.h SAMPLER/kmeanssampler.h SAMPLER/maxwellsampler.h SAMPLER/neuralsampler.h SAMPLER/problemsampler.h SAMPLER/rbfsampler.h SAMPLER/triangularsampler.h SAMPLER/uniformsampler.h $(DISTDIR)/
	$(COPY_FILE) --parents CORE/parameter.cpp CORE/parameterlist.cpp GE/cprogram.cc GE/doublestack.cc GE/fparser.cc GE/fpoptimizer.cc GE/grammargenetic.cpp GE/integeranneal.cpp GE/program.cc GE/rule.cc GE/symbol.cc INTERVAL/interval.cpp INTERVAL/intervalde.cpp INTERVAL/intervalproblem.cpp INTERVAL/problem.cpp METHODS/adam.cpp METHODS/armijosearch.cpp METHODS/bfgs.cpp METHODS/collection.cpp METHODS/doublebox.cpp METHODS/editlogger.cpp METHODS/fibonaccisearch.cpp METHODS/filelogger.cpp METHODS/genetic.cpp METHODS/goldensearch.cpp METHODS/gradientdescent.cpp METHODS/ipso.cpp METHODS/lbfgs.cpp METHODS/linesearch.cpp METHODS/logger.cpp METHODS/mean.cpp METHODS/optimizer.cpp METHODS/similarity.cpp MLMODELS/dataset.cpp MLMODELS/mlpproblem.cpp MLMODELS/model.cpp MLMODELS/rbfproblem.cpp SAMPLER/kmeanssampler.cpp SAMPLER/maxwellsampler.cpp SAMPLER/neuralsampler.cpp SAMPLER/problemsampler.cpp SAMPLER/rbfsampler.cpp SAMPLER/triangularsampler.cpp SAMPLER/uniformsampler.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -Ofast -O2 -O4 -fopenmp -march=native -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -ffast-math -fopt-info -Ofast -std=c++11 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

parameter.o: CORE/parameter.cpp CORE/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameter.o CORE/parameter.cpp

parameterlist.o: CORE/parameterlist.cpp CORE/parameterlist.h \
		CORE/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameterlist.o CORE/parameterlist.cpp

cprogram.o: GE/cprogram.cc GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cprogram.o GE/cprogram.cc

doublestack.o: GE/doublestack.cc GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublestack.o GE/doublestack.cc

fparser.o: GE/fparser.cc GE/fparser.hh \
		GE/fpconfig.hh \
		GE/fptypes.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fparser.o GE/fparser.cc

fpoptimizer.o: GE/fpoptimizer.cc GE/fpconfig.hh \
		GE/fparser.hh \
		GE/fptypes.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fpoptimizer.o GE/fpoptimizer.cc

grammargenetic.o: GE/grammargenetic.cpp GE/grammargenetic.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		CORE/parameterlist.h \
		CORE/parameter.h \
		GE/integeranneal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grammargenetic.o GE/grammargenetic.cpp

integeranneal.o: GE/integeranneal.cpp GE/integeranneal.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		INTERVAL/interval.h \
		INTERVAL/intervalproblem.h \
		GE/grammargenetic.h \
		CORE/parameterlist.h \
		CORE/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integeranneal.o GE/integeranneal.cpp

program.o: GE/program.cc GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o program.o GE/program.cc

rule.o: GE/rule.cc GE/rule.h \
		GE/symbol.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rule.o GE/rule.cc

symbol.o: GE/symbol.cc GE/symbol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symbol.o GE/symbol.cc

interval.o: INTERVAL/interval.cpp INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interval.o INTERVAL/interval.cpp

intervalde.o: INTERVAL/intervalde.cpp INTERVAL/intervalde.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		CORE/parameterlist.h \
		CORE/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intervalde.o INTERVAL/intervalde.cpp

intervalproblem.o: INTERVAL/intervalproblem.cpp INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intervalproblem.o INTERVAL/intervalproblem.cpp

problem.o: INTERVAL/problem.cpp INTERVAL/problem.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problem.o INTERVAL/problem.cpp

adam.o: METHODS/adam.cpp METHODS/adam.h \
		METHODS/optimizer.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		CORE/parameter.h \
		CORE/parameterlist.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		METHODS/goldensearch.h \
		METHODS/linesearch.h \
		METHODS/fibonaccisearch.h \
		METHODS/armijosearch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adam.o METHODS/adam.cpp

armijosearch.o: METHODS/armijosearch.cpp METHODS/armijosearch.h \
		METHODS/linesearch.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armijosearch.o METHODS/armijosearch.cpp

bfgs.o: METHODS/bfgs.cpp METHODS/bfgs.h \
		METHODS/optimizer.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		CORE/parameter.h \
		CORE/parameterlist.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bfgs.o METHODS/bfgs.cpp

collection.o: METHODS/collection.cpp METHODS/collection.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collection.o METHODS/collection.cpp

doublebox.o: METHODS/doublebox.cpp METHODS/doublebox.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublebox.o METHODS/doublebox.cpp

editlogger.o: METHODS/editlogger.cpp METHODS/editlogger.h \
		METHODS/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editlogger.o METHODS/editlogger.cpp

fibonaccisearch.o: METHODS/fibonaccisearch.cpp METHODS/fibonaccisearch.h \
		METHODS/linesearch.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fibonaccisearch.o METHODS/fibonaccisearch.cpp

filelogger.o: METHODS/filelogger.cpp METHODS/filelogger.h \
		METHODS/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filelogger.o METHODS/filelogger.cpp

genetic.o: METHODS/genetic.cpp METHODS/genetic.h \
		METHODS/collection.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		CORE/parameterlist.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genetic.o METHODS/genetic.cpp

goldensearch.o: METHODS/goldensearch.cpp METHODS/goldensearch.h \
		METHODS/linesearch.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o goldensearch.o METHODS/goldensearch.cpp

gradientdescent.o: METHODS/gradientdescent.cpp METHODS/gradientdescent.h \
		METHODS/optimizer.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		CORE/parameter.h \
		CORE/parameterlist.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		METHODS/linesearch.h \
		METHODS/fibonaccisearch.h \
		METHODS/goldensearch.h \
		METHODS/armijosearch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gradientdescent.o METHODS/gradientdescent.cpp

ipso.o: METHODS/ipso.cpp METHODS/ipso.h \
		METHODS/optimizer.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		CORE/parameter.h \
		CORE/parameterlist.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipso.o METHODS/ipso.cpp

lbfgs.o: METHODS/lbfgs.cpp METHODS/lbfgs.h \
		METHODS/optimizer.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		CORE/parameter.h \
		CORE/parameterlist.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lbfgs.o METHODS/lbfgs.cpp

linesearch.o: METHODS/linesearch.cpp METHODS/linesearch.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linesearch.o METHODS/linesearch.cpp

logger.o: METHODS/logger.cpp METHODS/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o METHODS/logger.cpp

mean.o: METHODS/mean.cpp METHODS/mean.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mean.o METHODS/mean.cpp

optimizer.o: METHODS/optimizer.cpp METHODS/optimizer.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		CORE/parameter.h \
		CORE/parameterlist.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		MLMODELS/dataset.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		METHODS/gradientdescent.h \
		METHODS/linesearch.h \
		METHODS/fibonaccisearch.h \
		METHODS/goldensearch.h \
		METHODS/armijosearch.h \
		METHODS/bfgs.h \
		METHODS/lbfgs.h \
		METHODS/adam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optimizer.o METHODS/optimizer.cpp

similarity.o: METHODS/similarity.cpp METHODS/similarity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o similarity.o METHODS/similarity.cpp

dataset.o: MLMODELS/dataset.cpp MLMODELS/dataset.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataset.o MLMODELS/dataset.cpp

mlpproblem.o: MLMODELS/mlpproblem.cpp MLMODELS/mlpproblem.h \
		MLMODELS/dataset.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		MLMODELS/model.h \
		CORE/parameterlist.h \
		CORE/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mlpproblem.o MLMODELS/mlpproblem.cpp

model.o: MLMODELS/model.cpp MLMODELS/model.h \
		MLMODELS/dataset.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		CORE/parameterlist.h \
		CORE/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o MLMODELS/model.cpp

rbfproblem.o: MLMODELS/rbfproblem.cpp MLMODELS/rbfproblem.h \
		MLMODELS/dataset.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		MLMODELS/model.h \
		CORE/parameterlist.h \
		CORE/parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rbfproblem.o MLMODELS/rbfproblem.cpp

kmeanssampler.o: SAMPLER/kmeanssampler.cpp SAMPLER/kmeanssampler.h \
		SAMPLER/problemsampler.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kmeanssampler.o SAMPLER/kmeanssampler.cpp

maxwellsampler.o: SAMPLER/maxwellsampler.cpp SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxwellsampler.o SAMPLER/maxwellsampler.cpp

neuralsampler.o: SAMPLER/neuralsampler.cpp SAMPLER/neuralsampler.h \
		SAMPLER/problemsampler.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		MLMODELS/dataset.h \
		METHODS/bfgs.h \
		METHODS/optimizer.h \
		CORE/parameter.h \
		CORE/parameterlist.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		METHODS/lbfgs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuralsampler.o SAMPLER/neuralsampler.cpp

problemsampler.o: SAMPLER/problemsampler.cpp SAMPLER/problemsampler.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problemsampler.o SAMPLER/problemsampler.cpp

rbfsampler.o: SAMPLER/rbfsampler.cpp SAMPLER/rbfsampler.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		SAMPLER/problemsampler.h \
		MLMODELS/dataset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rbfsampler.o SAMPLER/rbfsampler.cpp

triangularsampler.o: SAMPLER/triangularsampler.cpp SAMPLER/triangularsampler.h \
		SAMPLER/problemsampler.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o triangularsampler.o SAMPLER/triangularsampler.cpp

uniformsampler.o: SAMPLER/uniformsampler.cpp SAMPLER/uniformsampler.h \
		SAMPLER/problemsampler.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uniformsampler.o SAMPLER/uniformsampler.cpp

main.o: main.cpp MLMODELS/mlpproblem.h \
		MLMODELS/dataset.h \
		INTERVAL/intervalproblem.h \
		INTERVAL/interval.h \
		MLMODELS/model.h \
		CORE/parameterlist.h \
		CORE/parameter.h \
		MLMODELS/rbfproblem.h \
		GE/grammargenetic.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		METHODS/bfgs.h \
		METHODS/optimizer.h \
		METHODS/doublebox.h \
		METHODS/similarity.h \
		METHODS/mean.h \
		SAMPLER/maxwellsampler.h \
		SAMPLER/problemsampler.h \
		SAMPLER/neuralsampler.h \
		SAMPLER/triangularsampler.h \
		SAMPLER/uniformsampler.h \
		SAMPLER/rbfsampler.h \
		SAMPLER/kmeanssampler.h \
		METHODS/logger.h \
		METHODS/filelogger.h \
		METHODS/editlogger.h \
		METHODS/lbfgs.h \
		METHODS/adam.h \
		METHODS/goldensearch.h \
		METHODS/linesearch.h \
		METHODS/fibonaccisearch.h \
		METHODS/armijosearch.h \
		METHODS/gradientdescent.h \
		METHODS/ipso.h \
		METHODS/genetic.h \
		METHODS/collection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/GrammarNN/bin || mkdir -p $(INSTALL_ROOT)/opt/GrammarNN/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/GrammarNN/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/GrammarNN/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/GrammarNN/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/GrammarNN/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

